# Generated by Django 6.0.1 on 2026-02-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyplan_tasktemplate_team_dailytask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('candidates_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('triagem', 'Triagem'), ('entrevista', 'Entrevista'), ('final', 'Final'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dailytask',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='tasktemplateitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('responsible_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stage', models.CharField(choices=[('prospeccao', 'Prospeccao'), ('qualificacao', 'Qualificacao'), ('proposta', 'Proposta'), ('negociacao', 'Negociacao'), ('fechado', 'Fechado')], default='prospeccao', max_length=20)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='andamento', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('responsible_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to='api.userprofile')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DealGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_goals', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role_title', models.CharField(blank=True, default='', max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('manager_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('ferias', 'Ferias'), ('afastado', 'Afastado')], default='ativo', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_managed', to='api.userprofile')),
            ],
        ),
    ]
