# Generated by Django 6.0.1 on 2026-02-04 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_path', models.TextField(blank=True, default='')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('total_rows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lastro.scrapejob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
